- block:
    - name: start tuned daemon service
      service:
        name: tuned
        state: started
        enabled: yes
      when: optimization_tuned_activate

    - name: register tuned active profile
      shell: tuned-adm active
      register: tuned_check_profile
      changed_when: no

    - name: activate tuned selected profile
      command: "tuned-adm profile {{ optimizations_tuned_profile }}"
      when: >-
        optimization_tuned_activate
        and not tuned_check_profile.stdout is search(optimizations_tuned_profile)
  tags:
    - role::optimizations
    - role::optimizations::tuned
