---

dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint: "${MOLECULE_SCENARIO_DIRECTORY}/linters.sh"
platforms:
  - name: "centos7-${INSTANCE_UUID:-1}"
    box: centos/7
    memory: 1024
    groups:
      - molecule_hosts
      - molecule_hosts_centos
      - molecule_hosts_centos_7
  - name: "fedora32-${INSTANCE_UUID:-1}"
    box: fedora/32-cloud-base
    memory: 1024
    groups:
      - molecule_hosts
      - molecule_hosts_fedora
      - molecule_hosts_fedora_32
  - name: "fedora33-${INSTANCE_UUID:-1}"
    box: fedora/33-cloud-base
    memory: 1024
    groups:
      - molecule_hosts
      - molecule_hosts_fedora
      - molecule_hosts_fedora_33
provisioner:
  name: ansible
  config_options:
    defaults:
      callback_whitelist: profile_tasks
      action_plugins: PWD/action_plugins
  inventory:
    hosts:
      molecule_hosts:
        vars:
          optimizations_tuned_profile: throughput-performance
verifier:
  name: ansible
